### ISSUE TITLE
[Meta] Improve error experience

### ISSUE THREAD

**Issue by twelch** [seasketch/geoprocessing#101]
Currently users can get report errors if they try hard enough, usually shapes that are too large or complex for a given report.  The error messages are usually technical/vague, with no direction on what to do.  Reports that don't complete will stay in the loading state forever.  We can do better.

- [ ] ErrorBoundary doesn't seem to catch client runtime errors, in production (e.g. accessing object that is undefined)
- [ ] useFunction or maybe ResultCard could show a nicer error, or start with "Something went wrong with this report"
- [ ] if gp function doesn't return in timeout + X seconds, it likely won't ever return, client can report "Did not complete, this can happen with large or complex plans."
- [ ] Improve error logging with separation by project ID.  Gathers client and server side error metrics.  
- [ ] Warn user if plan size/complexity is greater than a specific amount

**Comment by twelch** [comment]
Here's the result of us-east-1 going down, can't even fetch the metadata.
![image](https://user-images.githubusercontent.com/81816/145079017-e3737c36-d4c5-4c5a-b583-d10f1b5d1496.png)
