### ISSUE TITLE
[Meta] Support subregional planning

### ISSUE THREAD

**Issue by twelch** [seasketch/geoprocessing#198]
Requirements:
- Must support both Azores (9 islands) and Maldives (26 atolls, 1000+ islands) uses cases
- Must support at least 1000 subregions (Maldives)
  - subregions can overlap (e.g. nearshore/offshore are subregions, plus individual levels of groupings underneath)
- Must be able to call useFunction() with additional parameters, which can vary per geoprocessing function.  For example, sending one or more `regions` to include in the run.
- GP function must be able to receive `geographies` parameter
- Precalc must be able to access geography boundaries (geographies.json), and iterate over them, clipping sketch to each before running the main geoprocessing function.  Metrics should use `geographyId` to differentiate.

Stretch requirements:
- A gp function Lambda (whether sync, or async run) must be able to execute additional lambdas, up to say 100 (for cost reasons), passing them smaller things to calculate and aggregate the result, allowing for parallelization.
  - child lambdas should be synchronous, immediately returning the result.  They will be independent standalone geoprocessing function

Risks:
- Size of files (precalc.json, regions.json)

Tasks:
- [x] subregion UI selector -- see Azores subregional branch
- [x] Extend useFunction to support multiple parameters.  Update geoprocessing handler (lambda) to receive additional parameters and cache results (#195)
- [x] Trim metrics payload size (#172)
- [x] Zero metrics when sketch doesn't overlap with geography (#203)
- [x] Make precalc geography-aware.  Decouple precalc from data import, datasources.json, and refactor keyStats structure (#196)
  - Migrate azores work into library (https://github.com/seasketch/azores-nearshore-reports/pull/11)
